name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.x

    - name: Setup Just
      uses: extractions/setup-just@v1
      with:
        just-version: 1.13.0

    - name: Verify formatting
      run: just fmt --check

    - name: Lint
      run: just lint

    - name: Type check
      run: just check-types

    - name: Run tests
      run: just test